name: Run Semgrep

on:
  workflow_dispatch:
    inputs:
      versionId:
        required: true
      callbackUrl:
        required: true
      repo:
        required: true
      ref:
        required: true
jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Clone target repository
        env:
          GH_TOKEN: ${{ secrets.PLATFORM_GITHUB_TOKEN }}
        run: |
          git clone --branch ${{ github.event.inputs.ref }} \
            https://$GH_TOKEN@github.com/${{ github.event.inputs.repo }} target-repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep and jq
        run: |
          pip install semgrep
          sudo apt-get update && sudo apt-get install -y jq

      - name: Run Semgrep and extract results only
        id: semgrep
        run: |
          mkdir -p output                                    # ✅ 공통 저장 경로
          cd target-repo
          if semgrep --config=p/default --sarif > ../output/full.sarif 2> ../output/error.log; then
            jq '.runs[0].results' ../output/full.sarif > ../output/results.json
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=fail" >> $GITHUB_OUTPUT
          fi

      - name: Debug extracted Semgrep results (for inspection)
        run: |
          echo "=== Extracted Semgrep Results ==="
          cat output/results.json                            # ✅ 항상 이 경로만 참조

      - name: Upload result to backend (optimized)
        run: |
          if [ "${{ steps.semgrep.outputs.status }}" = "success" ]; then
            curl -X POST "${{ github.event.inputs.callbackUrl }}?versionId=${{ github.event.inputs.versionId }}" \
              -H "Content-Type: application/json" \
              --data-binary @output/results.json
          else
            curl -X POST "${{ github.event.inputs.callbackUrl }}?versionId=${{ github.event.inputs.versionId }}" \
              -H "Content-Type: text/plain" \
              --data-binary @output/error.log
          fi
