name: Run Semgrep

on:
  workflow_dispatch:
    inputs:
      versionId:
        required: true
      callbackUrl:
        required: true
      repo:
        required: true
      ref:
        required: true

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Clone target repository
        env:
          GH_TOKEN: ${{ secrets.PLATFORM_GITHUB_TOKEN }}
        run: |
          git clone --branch ${{ github.event.inputs.ref }} \
            https://$GH_TOKEN@github.com/${{ github.event.inputs.repo }} target-repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep and save SARIF
        id: semgrep
        run: |
          mkdir -p output
          cd target-repo
          if semgrep --config=p/default --sarif > ../output/full.sarif 2> ../output/error.log; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=fail" >> $GITHUB_OUTPUT
          fi

      - name: Debug Semgrep full SARIF output
        if: steps.semgrep.outputs.status == 'success'
        run: |
          echo "=== Semgrep full SARIF ==="
          cat output/full.sarif

      - name: Upload result to backend
        run: |
          if [ "${{ steps.semgrep.outputs.status }}" = "success" ]; then
            echo "=== Uploading full SARIF JSON to backend ==="
            cat output/full.sarif
            curl -X POST "${{ github.event.inputs.callbackUrl }}?versionId=${{ github.event.inputs.versionId }}" \
              -H "Content-Type: application/json" \
              --data-binary @output/full.sarif
          else
            echo "=== Uploading error log to backend ==="
            cat output/error.log
            curl -X POST "${{ github.event.inputs.callbackUrl }}?versionId=${{ github.event.inputs.versionId }}" \
              -H "Content-Type: text/plain" \
              --data-binary @output/error.log
          fi

      - name: Upload SARIF artifact
        if: steps.semgrep.outputs.status == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: output/full.sarif
