name: Run Semgrep

on:
  workflow_dispatch:
    inputs:
      versionId:
        required: true
      callbackUrl:
        required: true
      repo:
        required: true
      ref:
        required: true

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Clone target repository
        env:
          GH_TOKEN: ${{ secrets.PLATFORM_GITHUB_TOKEN }}
        run: |
          git clone --branch ${{ github.event.inputs.ref }} \
            https://$GH_TOKEN@github.com/${{ github.event.inputs.repo }} target-repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep and jq
        run: |
          pip install semgrep
          sudo apt-get update && sudo apt-get install -y jq

      - name: Run Semgrep and parse result to custom format
        id: semgrep
        run: |
          mkdir -p output
          cd target-repo
          if semgrep --config=p/default --sarif > ../output/full.sarif 2> ../output/error.log; then
            jq '[.runs[0].results[] | {
              ruleId: .ruleId,
              message: .message.text,
              severity: .level,
              filePath: .locations[0].physicalLocation.artifactLocation.uri,
              line: .locations[0].physicalLocation.region.startLine,
              column: .locations[0].physicalLocation.region.startColumn,
              tags: (.properties.tags // [])
            } | {
              ruleId, message, severity, filePath, line, column,
              cwe: ( .tags[]? | select(test("^CWE-") ) ) // null,
              cve: ( .tags[]? | select(test("^CVE-") ) ) // null
            }]' ../output/full.sarif > ../output/results.json
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=fail" >> $GITHUB_OUTPUT
          fi

      - name: Upload result to backend
        run: |
          if [ "${{ steps.semgrep.outputs.status }}" = "success" ]; then
            curl -X POST "${{ github.event.inputs.callbackUrl }}?versionId=${{ github.event.inputs.versionId }}" \
              -H "Content-Type: application/json" \
              --data-binary @output/results.json
          else
            curl -X POST "${{ github.event.inputs.callbackUrl }}?versionId=${{ github.event.inputs.versionId }}" \
              -H "Content-Type: text/plain" \
              --data-binary @output/error.log
          fi